=== PDochev/hackathonparty/json-schema/entities/user_profile.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "placeholder",
    "title": "User Profile",
    "description": "A collection of a user's personal information",
    "type": "object",
    "properties": {
        "user_id": {
            "type": "string"
        },
        "name": {
            "type": "string"
        },
        "email": {
            "type": "string",
            "format": "email"
        },
        "address": {
            "type": "string"
        },
        "rank": {
            "type": "string"
        },
        "profile_pic_url": {
            "type": "string",
            "format": "uri"
        },
        "created_at": {
            "type": "string",
            "format": "date-time"
        },
        "updated_at": {
            "type": "string",
            "format": "date-time"
        }
    },
    "required": [
        "user_id",
        "name",
        "email",
        "address",
        "rank",
        "profile_pic_url",
        "created_at",
        "updated_at"
    ]
}

=== PDochev/hackathonparty/json-schema/responses/examples/example_response_to_get_user_profile_info.json
{
    "user_id": "person1",
    "name": "Dr. Person Being",
    "email": "personbeing@agent.com",
    "address": "8 Entity Road, Philosophia",
    "rank": "Newcomer",
    "profile_pic_url": "https://my-image-hosting-domain.com/personbeing_candid.jpg",
    "created_at": "1931-04-10T07:57:39.0Z",
    "updated_at" : "1931-04-10T07:57:39.0Z"
}
