=== PDochev/hackathonparty/json-schema/get_user_task_list.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "placeholder",
    "title": "User Task List",
    "description": "The list of tasks for a given user",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "task_id": {
                "type": "string"
            },
            "subtasks": {
                "type" : "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "subtask_id": {
                            "type": "string"
                        },
                        "title": {
                            "type": "string"
                        },
                        "description": {
                            "type": "string"
                        },
                        "instructions": {
                            "type": "string"
                        },
                        "created_at": {
                            "type": "string",
                            "format": "date-time"
                        },
                        "updated_at": {
                            "type": "string",
                            "format": "date-time"
                        },
                        "is_completed": {
                            "type": "boolean"
                        }
                    },
                    "required": [
                        "subtask_id",
                        "title",
                        "description",
                        "instructions",
                        "created_at",
                        "updated_at",
                        "is_completed"
                    ]
                }
            },
            "title": {
                "type": "string"
            },
            "description": {
                "type": "string"
            },
            "created_at": {
                "type": "string",
                "format": "date-time"
            },
            "updated_at": {
                "type": "string",
                "format": "date-time"
            }
        },
        "required": [
            "task_id",
            "subtasks",
            "title",
            "description",
            "created_at",
            "updated_at"
        ]
    }
}

=== PDochev/hackathonparty/json-schema/responses/examples/example_response_to_get_user_task_list.json
[
  {
    "task_id": "dolor in incididunt proident",
    "subtasks": [
      {
        "subtask_id": "dolore consequat",
        "title": "ut cillum laboris",
        "description": "reprehenderit nulla fugiat laborum in",
        "instructions": "aliquip incididunt fugiat qui",
        "created_at": "1944-01-15T09:32:29.0Z",
        "updated_at": "1921-02-25T03:34:31.0Z",
        "is_completed": false
      },
      {
        "subtask_id": "aliqua occaecat fugiat veniam esse",
        "title": "nulla aute pariatur veniam",
        "description": "dolor officia ullamco nisi",
        "instructions": "aliqua magna anim non elit",
        "created_at": "1935-07-21T13:55:11.0Z",
        "updated_at": "1904-03-25T21:55:50.0Z",
        "is_completed": true
      },
      {
        "subtask_id": "sunt amet fugiat",
        "title": "velit Excepteur Duis",
        "description": "adipisicing nisi occaecat",
        "instructions": "ex Ut",
        "created_at": "1914-03-18T22:58:52.0Z",
        "updated_at": "1893-10-20T07:51:15.0Z",
        "is_completed": false
      },
      {
        "subtask_id": "labore",
        "title": "sit quis",
        "description": "consectetur",
        "instructions": "ex et commodo exercitation",
        "created_at": "1933-10-23T07:56:41.0Z",
        "updated_at": "1891-01-27T02:03:03.0Z",
        "is_completed": true
      }
    ],
    "title": "anim esse",
    "description": "cupidatat",
    "created_at": "1914-01-12T14:31:56.0Z",
    "updated_at": "1940-08-30T19:28:27.0Z"
  }
]
